clear
install;

input_file = 'Triplet.wav';
block_size = 1024/2;
Volume = 0.5;
hrtf_sofa = SOFAload('BuK_ED_corr.sofa');

Input_stream = dsp.AudioFileReader(input_file,'SamplesPerFrame',block_size,'PlayCount',10);
Output_device = audioDeviceWriter('SampleRate',Input_stream.SampleRate,'BufferSize',block_size);

sound_scene_setup = struct(  ...
    'N_in',                     Input_stream.info.NumChannels,...
    'N_out',                    Output_device.info.MaximumOutputChannels,...
    'SampleRate',               Input_stream.SampleRate,...
    'Block_size',               block_size, ...
    'HRTF',                     hrtf_sofa, ...
    'Binauralization',          true,...
    'Downmixing_enabled',       true,...
    'Downmixing_mode',          'default',...
    'Loudspeaker_setup',        struct('Shape','circular','R',2,'N',2),...
    'Rendering_mode',           'VBAP',...
    'Renderer_setup',           [],...
    'Loudspeaker_type',         struct('Shape','point_source','R',0.05),...
    'Virtual_source_type',      struct('Shape','point_source','R',0.01));

sound_scene_setup.Renderer_setup = get_default_renderer_setup(sound_scene_setup.Rendering_mode);
sound_scene = sound_scene(listener_space_axes(axes),sound_scene_setup);

while ~isDone(Input_stream)
    output = Volume*sound_scene.render_sound_scene(Input_stream(), sound_scene_setup.Binauralization, sound_scene_setup.Downmixing_enabled );
    Output_device(output);
    drawnow limitrate
end
release(Output_device)
release(Input_stream)